[phases.setup]
nixPkgs = [
  "ffmpeg",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXcursor",
  "xorg.libXi",
  "glib",
  "gtk3",
  "pango",
  "cairo",
  "alsa-lib"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[start]
cmd = "python start.py"
